### ISSUE TITLE
Gm list modification

### ISSUE THREAD

**Issue by HyperSin** [huludini/pw-web#12]
I was wondering if instead of it showing the gm username if it could show char name instead and the gm role like admin, gm, head gm etc

**Comment by tomirons** [comment]
That isn't an option right now, nor do we plan on making it one. Sorry!

**Comment by BahaStriker** [comment]
I already found a solution for this 

insert GM name in any field like this
http://prntscr.com/a3szul

Now go to 
`resources/views/front`and edit `widgets.blade.php`

in line 5 it says 
`<li class="list-group-item"> {{ $gm->name }}`
change `name` to any field you filled 
like my example it would be 
`<li class="list-group-item"> {{ $gm->qq }}`

here's the result 
http://prntscr.com/a3t0pv

**Comment by HyperSin** [comment]
Thank you :)

**Comment by tomirons** [comment]
You realize when you update, that modification will be gone. You'll have to do it every time. So if your fine with that then go for it.
