### ISSUE TITLE
PaymentWall 

### ISSUE THREAD

**Issue by BahaStriker** [huludini/pw-web#13]
1st Payment wall is asking to replace "[USER_ID]" placeholder with id of end-user who is viewing the widget and I don't know how or what to do
http://prntscr.com/a6k37s

2nd when I put the iframe link and my secret key on panel I get this error after saving 
"The paymentwall key field is required."

**Comment by tomirons** [comment]
The **[USER_ID]** will be replaced automatically by the panel. I've fixed the second issue in the next release.
