### ISSUE TITLE
Paymentwall Ping back 

### ISSUE THREAD

**Issue by BahaStriker** [huludini/pw-web#14]
"Pingback wasn't successful. Reason: HTTP status code is different from 200" 

> Signature base string
> uid=1024currency=50type=0ref=HTEST500f6ec3446fb538aa073209f5dd26de854
> 
> Signature = MD5(Signature base string)
> 032de6e9c794f1d55ed0d2da38322db9
> 
> Request
> `GET http://panel.nexuspw.org:80/donate/paymentwall?uid=1024&currency=50&type=0&ref=HTEST500&is_test=1&sig=032de6e9c794f1d55ed0d2da38322db9 HTTP/1.1
> Host: panel.nexuspw.org
> Connection: close
> Accept-encoding: gzip, deflate
> User-Agent: Paymentwall API
> `
> Response
> `HTTP/1.0 405 Method Not Allowed
> Date: Thu, 25 Feb 2016 23:14:50 GMT
> Server: Apache/2.4.16 (Ubuntu)
> Allow: POST
> Content-length: 4519
> Content-type: text/html; charset=UTF-8
> Connection: close`

**Comment by tomirons** [comment]
This is now fixed in v1.0.2
