### ISSUE TITLE
Must get fixed bugs

### ISSUE THREAD

**Issue by BahaStriker** [huludini/pw-web#18]
- Make so they can be able to select char on mobile
- Make the voting checks the User ID and IP address instead of checking only IP
- Vouchers doesn't count how many times it was redeemed 
- Make Vouchers can only get redeemed once per User ID + IP instead of User ID only
- Enable how many times the Voucher should be redeemed before it expires
- Online Players function is totally wrong

I'm running this panel on a live Server so please I need those to get fixed asap x.x

**Comment by tomirons** [comment]
These aren't bugs, these are enhancements.

**Comment by tomirons** [comment]
Alright I've fixed the vouchers count issue, and added the following:
- Ability to select a character on a mobile device
- Voting will now use the User ID and IP address in the checks
- When redeeming a voucher, it will check by User ID and IP address
