### ISSUE TITLE
1.0.4 Bug

### ISSUE THREAD

**Issue by BahaStriker** [huludini/pw-web#19]
Voucher still can be redeemed by the same IP address, same goes for Voting they still can vote on the same user id if the IP was changed 

http://prntscr.com/aisygk

**Comment by HyperSin** [comment]
Hell i dont get cubi from voteing, panel currency works but when it comes to cubi the panel says fuck you, and does your factions in dashboard and in rankings work cause mine dont

**Comment by BahaStriker** [comment]
Cubi vote works for me, however I had to do a little script with a cron that runs every 5 minutes to fix the issue 
http://prntscr.com/ajchrj
as for factions, nope still nothing...
You can see my panel here : http://panel.nexuspw.org/

**Comment by HyperSin** [comment]
yeah factions is broken for me and voteing works it just takes like hours and hours for it to arrive ingame
