### ISSUE TITLE
pw-web

### ISSUE THREAD

**Issue by otlitake** [huludini/pw-web#24]
```
when i try to go to
public/index, it keep sending me to
public/index/admin/install   [page not found]
how i fix this?
i did all the steps on the tutorial, all was fine

Fixed --- Problem old PHP version
```

```
new issue...
The requested URL /pw-web/public/ was not found on this server.
Apache/2.4.7 (Ubuntu) Server at 192.1xx.xxx.xxx Port 80


Fixed --- Problem was sleepy and was typing wrong path ._.
```

Now serious problem....
when i turn on server, it says
_Whoops, looks like something went wrong._
only offline i can be on the panel, but when is online, is not working

**Comment by BahaStriker** [comment]
redo the permissions again.

**Comment by tomirons** [comment]
Sorry I didn't read the whole thing, I say "fixed" so i closed it...
Yeah, redo the permissions, it should fix the problem.
