### ISSUE TITLE
vote mmotop.ru

### ISSUE THREAD

**Issue by warrfar** [huludini/pw-web#26]
Hello hulu, please add voting through pw.mmotop.ru

**Comment by BahaStriker** [comment]
how does it work ? I mean I'm sure mmotop.ru have another system to count votes right ?

**Comment by warrfar** [comment]
80758900    01.04.2016 01:09:27 ip  login   1
80643027    01.04.2016 01:18:00 ip  login   1

**Comment by tomirons** [comment]
This isn't going to happen, sorry.
