### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by warrfar** [huludini/pw-web#28]
Hello, everything was working, but today there was an error Whoops, Whoops, looks like something went wrong. Just as there was, what to do?

**Comment by BahaStriker** [comment]
check in storage/logs/laravel.log what error it's throwing

**Comment by warrfar** [comment]
I decided to reset now when you install such an error https://i.gyazo.com/b5e4324072eff39cc525a8ef886cdd12.png

**Comment by warrfar** [comment]
??

**Comment by tomirons** [comment]
> check in storage/logs/laravel.log what error it's throwing

Do that...

**Comment by warrfar** [comment]
[2016-04-14 15:17:53] production.ERROR: exception 'PDOException' with message 'could not find driver' in /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
Stack trace:
#0 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=loca...', 'root', '123', Array)
#1 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(175): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Support/Facades/Schema.php(28): Illuminate\Database\DatabaseManager->connection()
#7 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(120): Illuminate\Support\Facades\Schema::getFacadeAccessor()
#8 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(205): Illuminate\Support\Facades\Facade::getFacadeRoot()
#9 /var/www/html/pw-web-master/app/Providers/ViewServiceProvider.php(99): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#10 /var/www/html/pw-web-master/app/Providers/ViewServiceProvider.php(99): Illuminate\Support\Facades\Schema::hasTable('pweb_settings')
#11 [internal function]: App\Providers\ViewServiceProvider->boot()
#12 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#14 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\ViewServiceProvider))
#15 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\ViewServiceProvider), 18)
#16 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#17 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#18 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#19 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#20 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#21 /var/www/html/pw-web-master/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#22 /var/www/html/pw-web-master/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#23 /var/www/html/pw-web-master/server.php(21): require_once('/var/www/html/p...')
#24 {main}

**Comment by warrfar** [comment]
ErrorException in 733211db87eb8c1cc2da3aa208abc685 line 5:
Trying to get property of non-object (View: /var/www/html/web/resources/views/front/widgets.blade.php) (View: /var/www/html/web/resources/views/front/widgets.blade.php) (View: /var/www/html/web/resources/views/front/widgets.blade.php)

**Comment by warrfar** [comment]
new probles, help pls 
ErrorException in 733211db87eb8c1cc2da3aa208abc685 line 5:
Trying to get property of non-object (View: /var/www/html/web/resources/views/front/widgets.blade.php) (View: /var/www/html/web/resources/views/front/widgets.blade.php) (View: /var/www/html/web/resources/views/front/widgets.blade.php)

**Comment by warrfar** [comment]
help pls

**Comment by tomirons** [comment]
Seriously, you need to calm down, I'll help you when I have the time. If you bump another issue with "help pls" or "??" again, I will not even respond to your issues and just close them. I don't work for you and this panel is open source, so therefore I'll answer you when I want to.

**Comment by warrfar** [comment]
Okay, sorry,
I just can not understand what the problem is, private office and he worked in itself has stopped working, the logs give a strange problem ..
