### ISSUE TITLE
Issue After Fill up System Setting

### ISSUE THREAD

**Issue by dietchse** [huludini/pw-web#30]
Hello Hulu this is great release 
But i Have a little issue here, after the step system setting, it show Error "Whoops, looks like something went wrong."

Here is my laravel log

`[2016-06-09 18:09:11] production.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /var/www/html/panel/bootstrap/cache/compiled.php:2927
Stack trace:
#0 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/html/panel/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#2 /var/www/html/panel/bootstrap/cache/compiled.php(12961): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#3 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /var/www/html/panel/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#5 /var/www/html/panel/bootstrap/cache/compiled.php(11555): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /var/www/html/panel/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#8 /var/www/html/panel/bootstrap/cache/compiled.php(12698): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /var/www/html/panel/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#11 /var/www/html/panel/bootstrap/cache/compiled.php(12635): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/html/panel/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#14 /var/www/html/panel/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/html/panel/bootstrap/cache/compiled.php(9585): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/panel/bootstrap/cache/compiled.php(9575): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /var/www/html/panel/bootstrap/cache/compiled.php(2254): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/html/panel/bootstrap/cache/compiled.php(2237): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#21 /var/www/html/panel/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#22 {main}

`

Thanks in advance

Regrats

**Comment by peterwedge** [comment]
Hi guy, you fixed the error ?
I have same problem, and not work ;( 
if you fixed, help me please.
thx
