### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by peterwedge** [huludini/pw-web#32]
Hi guys.
I have one error in my PW-WEb.
this error is Whoops, looks like something went wrong.
http://prntscr.com/bttzq8

Please, someone help-me ?
thx

**Comment by MrRiZZaH** [comment]
Same error here when entering public it sends me to public/admin/install and then says "Whoops...", any idea Hulu?

**Comment by MrRiZZaH** [comment]
Allright, never mind I figured out you need to chmod 777 the STORAGE folder too, might want to add this too the guide ;)
