### ISSUE TITLE
Can not log in, can not use!

### ISSUE THREAD

**Issue by MemorLi** [huludini/pw-web#37]
one  Page display : Whoops, looks like something went wrong.

two ：Is page layout out of order, environment or website?

**Comment by tomirons** [comment]
Check the error log to see what's wrong, and the layout is not _out of order_.

P.S. This panel is no longer supported by me and **will not** be updated by **me**, however I will still answer questions about it.

**Comment by MemorLi** [comment]
Thank you for your answer, this WEB design quite complex! Not suitable for ordinary people

**Comment by tomirons** [comment]
@MemorLi I don't it's not complex at all. It's based off of Laravel, which is very easy to learn.

If you want to get into it I would suggest looking at this **FREE** series: [Laracasts](https://laracasts.com/series/laravel-from-scratch-2017)

If you get into it and you'd like to update this panel to the most recent version of laravel (5.4) you're more than welcome to submit a PR.

**Comment by MemorLi** [comment]
I can enter the panel, the database is normal, login error, show: [Whoops, looks like something went wrong.] I do not know my PHP environment

**Comment by tomirons** [comment]
@MemorLi 

1. Go to `{website root}/storage/logs`
2. Open `laravel.log`
3. Copy the **last** error in the file (**not** the whole file)
4. Paste it in a reply

The information you're giving me is so vague cause laravel doesn't want to display exactly where the error is located with the application environment is set to `production`. Any error you get will usually just say **Whoops, looks like something went wrong** in the browser.

**Comment by MemorLi** [comment]
@tomirons

#63 /var/www/html/pweb/bootstrap/cache/compiled.php(2254): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/html/pweb/bootstrap/cache/compiled.php(2237): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /var/www/html/pweb/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 /var/www/html/pweb/server.php(21): require_once('/var/www/html/p...')
#67 {main}

**Comment by tomirons** [comment]
@MemorLi scroll up to where it says **# 1** and get me the message above that.

**Comment by MemorLi** [comment]
[2017-03-11 01:06:05] production.ERROR: exception 'Intervention\Image\Exception\NotSupportedException' with message 'GD Library extension not available with this PHP installation.' in /var/www/html/pweb/vendor/intervention/image/src/Intervention/Image/Gd/Driver.php:16
Stack trace:
#0 /var/www/html/pweb/vendor/intervention/image/src/Intervention/Image/ImageManager.php(107): Intervention\Image\Gd\Driver->__construct()
#1 /var/www/html/pweb/vendor/intervention/image/src/Intervention/Image/ImageManager.php(64): Intervention\Image\ImageManager->createDriver()
#2 /var/www/html/pweb/bootstrap/cache/compiled.php(6029): Intervention\Image\ImageManager->canvas(100, 100)
#3 /var/www/html/pweb/vendor/laravolt/avatar/src/Avatar.php(251): Illuminate\Support\Facades\Facade::__callStatic('canvas', Array)
#4 /var/www/html/pweb/vendor/laravolt/avatar/src/Avatar.php(251): Intervention\Image\Facades\Image::canvas(100, 100)
#5 /var/www/html/pweb/vendor/laravolt/avatar/src/Avatar.php(84): Laravolt\Avatar\Avatar->buildAvatar()
#6 /var/www/html/pweb/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(239): Laravolt\Avatar\Avatar->Laravolt\Avatar\{closure}()
#7 [internal function]: Illuminate\Cache\Repository->rememberForever('192af2a0792a8ad...', Object(Closure))
#8 /var/www/html/pweb/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(318): call_user_func_array(Array, Array)
#9 /var/www/html/pweb/vendor/laravolt/avatar/src/Avatar.php(87): Illuminate\Cache\CacheManager->__call('rememberForever', Array)
#10 /var/www/html/pweb/vendor/laravolt/avatar/src/Avatar.php(87): Illuminate\Cache\CacheManager->rememberForever('192af2a0792a8ad...', Object(Closure))
#11 /var/www/html/pweb/storage/framework/views/e7fa442ec4207552dc4a186535249ede(87): Laravolt\Avatar\Avatar->toBase64()

**Comment by tomirons** [comment]
Do me a favor and Google _GD Library extension not available with this PHP installation._ and get that issue fixed.

**Comment by MemorLi** [comment]
Is the PHP version of the problem? PHP5.6.30

**Comment by tomirons** [comment]
It may be, try updating it to 7.0 and see if that fixes it.

**Comment by tomirons** [comment]
Since there hasn't been a response to this issue in more than 3 days I'm assuming this issue has been fixed.

**Comment by MemorLi** [comment]
Still problem！！！！！

**Comment by MemorLi** [comment]
A video guide？？

**Comment by tomirons** [comment]
Have you upgraded your PHP version to 7.x? If not, I would start there.

**Comment by MemorLi** [comment]
I have not used 7 you started from 7

**Comment by tomirons** [comment]
Try upgrading your PHP to 7.x and see if you can install the extension then.

**Comment by MemorLi** [comment]
OK

**Comment by MemorLi** [comment]
PHP7 environment is not suitable, you use PHP5

**Comment by tomirons** [comment]
I'm not sure what to tell you, maybe the way your server is setup is causing this issue.
