### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by shiank98** [huludini/pw-web#38]
I'm getting these errors when I try to install pw-web 

`PHP Parse error:  syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /var/www/pwweb/artisan on line 31
`

**Comment by shiank98** [comment]
after reinstalling it , i found this error on my Terminal
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.


  Problem 1
    - Installation request for danielstjules/stringy 1.10.0 -> satisfiable by danielstjules/stringy[1.10.0].
    - danielstjules/stringy 1.10.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for guzzle/guzzle v3.9.3 -> satisfiable by guzzle/guzzle[v3.9.3].
    - guzzle/guzzle v3.9.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 3
    - Installation request for knplabs/github-api 1.5.1 -> satisfiable by knplabs/github-api[1.5.1].
    - knplabs/github-api 1.5.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 4
    - Installation request for laravel/framework v5.1.29 -> satisfiable by laravel/framework[v5.1.29].
    - laravel/framework v5.1.29 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 5
    - Installation request for paymentwall/paymentwall-php 2.1.0 -> satisfiable by paymentwall/paymentwall-php[2.1.0].
    - paymentwall/paymentwall-php 2.1.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 6
    - Installation request for phpunit/phpunit 4.8.23 -> satisfiable by phpunit/phpunit[4.8.23].
    - phpunit/phpunit 4.8.23 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 7
    - danielstjules/stringy 1.10.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravolt/avatar 0.3.3 requires danielstjules/stringy ~1.8 -> satisfiable by danielstjules/stringy[1.10.0].
    - Installation request for laravolt/avatar 0.3.3 -> satisfiable by laravolt/avatar[0.3.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/5.6/cli/php.ini
    - /etc/php/5.6/cli/conf.d/10-opcache.ini
    - /etc/php/5.6/cli/conf.d/10-pdo.ini
    - /etc/php/5.6/cli/conf.d/20-calendar.ini
    - /etc/php/5.6/cli/conf.d/20-ctype.ini
    - /etc/php/5.6/cli/conf.d/20-exif.ini
    - /etc/php/5.6/cli/conf.d/20-fileinfo.ini
    - /etc/php/5.6/cli/conf.d/20-ftp.ini
    - /etc/php/5.6/cli/conf.d/20-gettext.ini
    - /etc/php/5.6/cli/conf.d/20-iconv.ini
    - /etc/php/5.6/cli/conf.d/20-json.ini
    - /etc/php/5.6/cli/conf.d/20-phar.ini
    - /etc/php/5.6/cli/conf.d/20-posix.ini
    - /etc/php/5.6/cli/conf.d/20-readline.ini
    - /etc/php/5.6/cli/conf.d/20-shmop.ini
    - /etc/php/5.6/cli/conf.d/20-sockets.ini
    - /etc/php/5.6/cli/conf.d/20-sysvmsg.ini
    - /etc/php/5.6/cli/conf.d/20-sysvsem.ini
    - /etc/php/5.6/cli/conf.d/20-sysvshm.ini
    - /etc/php/5.6/cli/conf.d/20-tokenizer.ini

**Comment by tomirons** [comment]
It seems that you need to install them, and it's as easy as doing `apt-get install php5-{extension}`.

**Comment by tomirons** [comment]
I'm assuming this issue has been fixed, if you have anymore problems please create another issue.
