### ISSUE TITLE
online/offline

### ISSUE THREAD

**Issue by HyperSin** [huludini/pw-web#4]
server online offline dont work, doesn't like the ip change, does 500 http:// error when you change the ip to your server ip

**Comment by tomirons** [comment]
Does your `storage` directory and all files inside have all permissions?

**Comment by HyperSin** [comment]
Yes you seen the problem for yourself

**Comment by HyperSin** [comment]
ok, with the ip change it works (with the server OFFLINE) but when you turn on the server the panel does this 

Server error
500

**Comment by tomirons** [comment]
Make sure your `bootstrap/cache` folder has 775 permissions.

**Comment by HyperSin** [comment]
Var/www/pw-web everything including the folder is 0777, what path is the bootstrap and cache at

**Comment by tomirons** [comment]
You should see the bootstrap folder inside the root directory of the application.

**Comment by HyperSin** [comment]
Then its got the permissions

**Comment by tomirons** [comment]
Can you please provide some logs from `storage/logs`? That will tell us what's going on.

**Comment by HyperSin** [comment]
[laravel.txt](https://github.com/huludini/pw-web/files/72723/laravel.txt)

**Comment by tomirons** [comment]
The details of this issue aren't adding up, I've done the install on different environments and I haven't had an issue. Maybe the environments are different, but I don't think that would cause the application to give a 500 error.

The error in the text file is a little different, that has something to do with the API. I'll mark this as a bug until I can clarify it otherwise.

**Comment by HyperSin** [comment]
Is it a error on my side?

**Comment by tomirons** [comment]
I don't think so, I've added a few lines to one of the API functions that might help fix this error.

Please re-install the panel.

**Comment by HyperSin** [comment]
How do i reinstall

**Comment by tomirons** [comment]
There is a guide on the repository page - https://github.com/huludini/pw-web

**Comment by HyperSin** [comment]
turned the server on and the error come back

Log File: [laravel.txt](https://github.com/huludini/pw-web/files/73277/laravel.txt)

**Comment by tomirons** [comment]
Try changing your server version. This is my last suggestion, I don't know what else it could be.

**Comment by HyperSin** [comment]
Ok, if it dont work, ill try to fix it and tell you what fixed it

**Comment by tomirons** [comment]
Since I can't find the reason, I'm closing the issue. If you happen to find something that may help us solve it then please leave another comment and we'll take another look.
