### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by UltimateCodeLove** [huludini/pw-web#40]
I followed every step but when it comes to database migration part it gives me this error.

[img]http://i.imgur.com/YE6yY3D.png[/img]

**Comment by tomirons** [comment]
That's a sign that you didn't run the `composer install` command.

**Comment by UltimateCodeLove** [comment]
Thanks for your fast reply. 

I managed to install it perfectly, but how do I access the website now? It is located in /var/www/pw-web/ but it keeps on saying "Forbidden, You don't have permission to access /pw-web/public on this server."

**Comment by UltimateCodeLove** [comment]
Never mind I managed to fix it by myself. Thanks anyway!

**Comment by tomirons** [comment]
I'm glad the issue has been fixed, if you need anything else feel free to create another issue.
