### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by UltimateCodeLove** [huludini/pw-web#41]
Hello there,

How can I add this cronjob "* * * * * php /var/www/pw-web/artisan schedule:run >> /dev/null 2>&1"?

Thank you!

**Comment by tomirons** [comment]
This should help you, [how to add cronjob to linux](https://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/).

**Comment by UltimateCodeLove** [comment]
Thank you!
