### ISSUE TITLE
Cubi Gold Not Sent

### ISSUE THREAD

**Issue by UltimateCodeLove** [huludini/pw-web#42]
I really love this user panel but sometimes when I vote, the gold never arrives. I use 4 sites and they give 50 silver each, the panel currently has XtremeTop100, Gtop100, TopG and Top 100 Arena. I don't know where waited Cubi Gold are, so I am not sure where to look for logs.

My panel is hosted on a different VPS than my game server. I am not sure if it has an effect on this.

**Comment by tomirons** [comment]
Does this happen occasionally or is it consistent?

**Comment by UltimateCodeLove** [comment]
It seems the problem resolved on its own somehow...

**Comment by tomirons** [comment]
They get added to a table and then every minute (if you have the scheduler setup) more will be added. So one transfer from website to game could take up to 10 minutes, if nothing goes horribly wrong.

**Comment by UltimateCodeLove** [comment]
I did realise this now.

By the way, is it possible to make the panel to force players to sign up with lower case letters? It somehow prevents players from logging into the game when they use capital letters.

Also, will you make this panel support 1.5.3 and will there be any updates in the upcoming future?

Thank you!

**Comment by tomirons** [comment]
You can force that to happen if you edit the source. I don't plan on making any updates to this panel since I don't mess with MMORPG's anymore.

**Comment by UltimateCodeLove** [comment]
I am willing to learn. Is it possible for you to send me a link to a guide or something for developing this panel?

I really like the layout and I can develop it.

**Comment by tomirons** [comment]
All you need to do is fork this repo, make changes, and send pull requests. It's not hard at all. 😄

**Comment by UltimateCodeLove** [comment]
I see. Ty
