### ISSUE TITLE
how to allocate administrator

### ISSUE THREAD

**Issue by slither74** [huludini/pw-web#46]
hi,

i was wondering if you could point me in the right direction to were i can make myself admin of the site.

thanks for your time 

Baz

**Comment by tomirons** [comment]
This is typically done in during the installation process, but you can manually change roles with direct access to the database.

Find your `users` table and your username, then update the `role` column to _administrator_.

**Comment by slither74** [comment]
Hi,

 ok thanks for your time :)

**Comment by tomirons** [comment]
No problem, let me know if there is anything else I can help you with.
