### ISSUE TITLE
ErrorException in EmptyCharacterIfServerOffline.php

### ISSUE THREAD

**Issue by HyperSin** [huludini/pw-web#5]
ErrorException in EmptyCharacterIfServerOffline.php line 20:
Undefined property: Huludini\PerfectWorldAPI\API::$online

Log File: [laravel.txt](https://github.com/huludini/pw-web/files/72927/laravel.txt)

**Comment by HyperSin** [comment]
install just finished , this come up the first time trying to open the panel

**Comment by tomirons** [comment]
Seems you don't have the latest version of the API. Try running `composer install` or `composer update`. If that doesn't work run `composer clearcache` and run `composer install` or `composer update` again.

**Comment by HyperSin** [comment]
Ok ill do it tomorrow when i wake up and tell you how it went

**Comment by tomirons** [comment]
Let us know if you come across this issue again.
