### ISSUE TITLE
Widget Online player unresponsive

### ISSUE THREAD

**Issue by Ramonymous** [huludini/pw-web#56]
Hello, your widget not generating online user correctly,
Ex : "I have a online player more than 80+. but i check the panel is only show random (from 10-16) only"
but, i fix this with this code : 

>      <span data-counter=counterup data-value=**<?php readfile("http://repo.paradise-world.top/stats/for-iframe.php"); ?>**</ span>

_http://repo.paradise-world.top/stats/for-iframe.php_ <- this generated from mysql

sorry for my bad english :)

**Comment by Yuuki-Clouds** [comment]
@Ramonymous Hallo Brother Help Me Please .. 
how to make Online player @pw-web ... "http://repo.paradise-world.top/stats/status-server.php"
Please Brother ..

**Comment by Ramonymous** [comment]
search on RZ Forum bro, Simple Status server information at pw section

**Comment by Yuuki-Clouds** [comment]
thx brother if work ...  thx

Pada tanggal Min, 1 Jul 2018 pukul 00.25 Rama Pamungkas <
notifications@github.com> menulis:

**Comment by Ramonymous** [comment]
np broo, hehe dont forget to play with us in my private server
www.paradise-world.org

2018-07-13 10:08 GMT+07:00 windsen1 <notifications@github.com>:
