### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by HyperSin** [huludini/pw-web#8]
1. Store items have no icons
2. If your coins are the same amount as what the item price is, it throws a error saying you dont have enough coins
3. Item doesn't send or never came
4. Select a character is broken
   - When selecting a character it says role already selected
   - When trying to select another character the panel goes to the Whoops, looks like something went wrong
5. Deleteing a item from the shop dont work untill you refesh the page
6. Voucher redeem code, when trying to redeem code it says you must select a character before proceeding and when you go to select a character it says role already selected, then trying to redeem the code again does it over again
7. Level up needs a cap level setting so people cant pass your servers cap level
8. Game status in dashboard dont work, all values stay 0

**Comment by tomirons** [comment]
1. Fixed
2. Fixed
3. I believe it's fixed, not sure without testing it though.
4. If you can please elaborate a little more. Did you have a character selected prior to selecting a new one?
5. Fixed
6. Sounds like it will be resolved once 4 gets fixed.
7. Will be added soon.
8. Uses the database for the characters, factions and registered players. If you have the cron jobs setup and its getting the roles/factions from the server then it should show. Then it uses the API to count the list of online players.

**Comment by HyperSin** [comment]
1. Is fixed
2. Is fixed
3. Needs a protection, you can buy stuff without selecting a char, 3 has the problem related to 4, it ant sending cause it dont know where to send it so it just takes your money
4. Idk how else to explain,  id have to show you and if the role was or wasn't selected, i couldn't tell sence it dont work all that well
5. Is fixed
6. Most likely
7. Ok
8.  Online players and registered accounts work on the main page, and idk about the other 2

**Comment by HyperSin** [comment]
1. Dropped
2. Dropped
3. Is Fixed
4. broke all to hell (ErrorException in API.php line 50: Undefined index: getRole)
5. Dropped
6. havent tested
7. Dropped
8. Dropped

**Comment by tomirons** [comment]
Everything in this issue has been fixed except 7 which will be added in a later version.
