### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by HyperSin** [huludini/pw-web#9]
on the main page, can you add gm online status with char select by role

**Comment by tomirons** [comment]
What do you mean? Like a list of Online GM's?

**Comment by HyperSin** [comment]
Like online offline status, like Admin : HyperSin "Green" Online or "Red" or "Gray" Offline

**Comment by tomirons** [comment]
I guess that's a good idea, but the next problem I have is how to display it... since it can't look like the normal widgets. I'll figure it out and update the demo with it.

**Comment by HyperSin** [comment]
Well if it cant be done its ok

**Comment by tomirons** [comment]
It has been completed, you won't see it til the next update though.
